name       : python-stopit
version    : 1.1.2
release    : 1
source     :
    - https://files.pythonhosted.org/packages/35/58/e8bb0b0fb05baf07bbac1450c447d753da65f9701f551dca79823ce15d50/stopit-1.1.2.tar.gz : f7f39c583fd92027bd9d06127b259aee7a5b7945c1f1fa56263811e1e766996d
license    : MIT
component  : programming.python
summary    : Timeout control decorator and context managers, raise any exception in another thread
description: |
    Raise asynchronous exceptions in other threads, control the timeout of blocks or callables with two context managers and two decorators.
build      : |
    %python3_setup
install    : |
    %python3_install
